# Generated by Django 5.1.4 on 2025-01-04 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0003_order_done'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(default='Не указан', max_length=250),
        ),
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='Не указан', max_length=250),
        ),
        migrations.AddField(
            model_name='order',
            name='last_name',
            field=models.CharField(default='Не указан', max_length=250),
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default='Не указан', max_length=25),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid',
            field=models.BooleanField(default=True),
        ),
    ]
