# Generated by Django 5.1.4 on 2025-01-04 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0004_alter_order_options_order_address_order_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Позиция заказа', 'verbose_name_plural': 'Позиции заказа'},
        ),
    ]
