# Generated by Django 5.1.4 on 2025-01-06 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0005_alter_orderitem_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('date',), 'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='sort',
            options={'verbose_name': 'Сорт', 'verbose_name_plural': 'Сорта'},
        ),
    ]
